AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 200

Metrics/BlockLength:
  Max: 200

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
