name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.5'
    env:
      OPENAI_ACCESS_TOKEN: ${{ secrets.OPENAI_ACCESS_TOKEN }}
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
      OPENAI_LOG_ERRORS: ${{ secrets.OPENAI_LOG_ERRORS }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
      - name: Run Coveralls
        if: ${{ (github.event_name == 'pull_request' && github.ref != 'refs/heads/master') || (github.event_name == 'push' && github.ref == 'refs/heads/master') }}
        uses: coverallsapp/github-action@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/lcov.info"
